### PR TITLE
master-qa-46882

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-46882

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @yuwanyang ， I edit your commit message.

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom/liferay-portal#68601

**Pull request closed without merging**
