### PR TITLE
master-qa-41982

### PR DESCRIPTION
**Pull request by yuwanyang**
https://issues.liferay.com/browse/LRQA-41982

### CODE REVIEW

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by yuwanyang** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Hi @yuwanyang , I add back the locale in case since it works after you setting the property in portal-ext.properties.

**Comment by liulukiwi** [comment]
Pushed to GRen.
GinsonRen#233.

**Pull request closed without merging**
