### PR TITLE
LPS-144586

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LPS-144586
https://issues.liferay.com/browse/LPS-144529

### CODE REVIEW

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Just started reviewing :)

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Hi @catarineaguiar , changes made in https://github.com/liulukiwi/liferay-portal/pull/377

**Pull request closed without merging**
