### PR TITLE
master-qa-46005

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-46005

This is for master only, thanks!

cc/ @GinsonRen, @brianwulbern

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
Pushed to Bchan.
master: brianchandotcom/liferay-portal#66783

**Pull request closed without merging**
