### PR TITLE
master-qa-45971

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-45971

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @HarryC0204 ,
I update the case to use LexiconCard.clickCard just like SitePages#_selectPageType, so card.macro is removed.

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom/liferay-portal#68747

**Pull request closed without merging**
