### PR TITLE
LRQA-55188, LRQA-55189, LRQA-55290 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-55188
https://issues.liferay.com/browse/LRQA-55189
https://issues.liferay.com/browse/LRQA-55290

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
I add addtional fix for changes in LRQA-56111 and remove unnecessary step.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/85481

**Pull request closed without merging**
