### PR TITLE
master-qa-46818

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-46818

This is for master only.

/cc @GinsonRen

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
Pushed to Bchan.
brianchandotcom/liferay-portal#68186

**Pull request closed without merging**
