### PR TITLE
master-qa-126603

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-126603
Submit to master.

cc @tonyma888

### CODE REVIEW

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:test:sf

**Comment by chaowang-123** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Hi @chaowang-123 , I remove property in case to run the case.

**Comment by liulukiwi** [comment]
Pushed to liferay-echo.
https://github.com/liferay-echo/liferay-portal/pull/3548

**Pull request closed without merging**
