### PR TITLE
master-qa-44691

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRQA-44691

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by suilin** [comment]
ci:test:revelant

**Comment by suilin** [comment]
cc @GinsonRen @brianwulbern

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom/liferay-portal#66953

**Pull request closed without merging**
