### PR TITLE
master-qa-46059

### PR DESCRIPTION
**Pull request by HarryC0204**
https://issues.liferay.com/browse/LRQA-46059
This issue affect both master & 7.1.x

### CODE REVIEW

**Comment by HarryC0204** [comment]
ci:test:sf

**Comment by HarryC0204** [comment]
ci:test:revelant

**Comment by HarryC0204** [comment]
cc @brianwulbern @GinsonRen

**Comment by liulukiwi** [comment]
Pushed to Bchan.
master: brianchandotcom#66783

**Pull request closed without merging**
