### PR TITLE
master-qa-45302

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-45302

This is for master only.

cc/ @GinsonRen, @brianwulbern

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
No test changes needed :)

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom/liferay-portal#66503

**Pull request closed without merging**
