### PR TITLE
master-qa-46819

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-46819

This is for master only.

/cc @GinsonRen

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @zhangyan0701 , edit your commit message

**Comment by liulukiwi** [comment]
Pushed to Bchan.
[brianchandotcom#68186](https://github.com/brianchandotcom/liferay-portal/pull/68186)

**Pull request closed without merging**
