### PR TITLE
master-qa-43341

### PR DESCRIPTION
**Pull request by zhangyan0701**
https://issues.liferay.com/browse/LRQA-43341

### CODE REVIEW

**Comment by zhangyan0701** [comment]
ci:test:sf

**Comment by zhangyan0701** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi Summer Zhang, I replace the lar file and change the case lar name back.

**Comment by liulukiwi** [comment]
Pushed to BChan.
brianchandotcom#64352

**Pull request closed without merging**
