### PR TITLE
master-qa-54275

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-54275

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
No test changes needed :)
could also click back button like john co did:
https://github.com/liferay/liferay-portal/commit/7cdc8ef1b503440d296986a136b63bedf58750ac

**Pull request closed without merging**
